# rewind bash integration
# Generated by `rw init bash`.
# Install with:   rw init --install
# Remove with:    rw init --uninstall

__rewind_sock_dir() {
    printf '%s\n' "${XDG_DATA_HOME:-$HOME/.local/share}/rewind"
}

__rewind_sock_path() {
    printf '%s\n' "$(__rewind_sock_dir)/rewind.sock"
}

__rewind_now_ms() {
    python3 -c 'import time; print(int(time.time() * 1000))'
}

__rewind_json_string() {
    python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}

__rewind_daemon_start() {
    local sock_dir sock
    sock_dir="$(__rewind_sock_dir)"
    sock="$(__rewind_sock_path)"

    # If the socket exists, assume the daemon is already available.
    [[ -S "$sock" ]] && return 0

    mkdir -p "$sock_dir"

    # Start from a subshell so interactive bash does not print `[1] pid`.
    ( rw-daemon >/dev/null 2>&1 </dev/null & )

    # Give the daemon a brief chance to bind before the first hook fires.
    sleep 0.05
}

__rewind_should_skip() {
    local cmd="$1"

    [[ -z "$cmd" ]] && return 0

    case "$cmd" in
        rw|rw\ *|rw-daemon|rw-daemon\ *)
            return 0
            ;;
    esac

    return 1
}

__rewind_debug_trap() {
    local previous_status=$?

    # Avoid recording commands executed by rewind's own hook functions.
    [[ "${__rewind_in_hook:-0}" == "1" ]] && return "$previous_status"

    case "${FUNCNAME[1]:-}" in
        __rewind_*)
            return "$previous_status"
            ;;
    esac

    case "$BASH_COMMAND" in
        __rewind_*|trap\ *|PROMPT_COMMAND=*|history\ *)
            return "$previous_status"
            ;;
    esac

    __rewind_start_time="$(__rewind_now_ms)"
    __rewind_last_cmd="$BASH_COMMAND"

    return "$previous_status"
}

__rewind_prompt_command() {
    local exit_code=$?

    __rewind_in_hook=1
    __rewind_record "$exit_code"

    # Preserve the user's previous PROMPT_COMMAND if one existed before rewind.
    if [[ -n "${__rewind_original_prompt_command:-}" ]]; then
        eval "$__rewind_original_prompt_command"
    fi

    __rewind_in_hook=0

    return "$exit_code"
}

__rewind_record() {
    local exit_code="$1"
    local end_time start_time duration cmd sock encoded_cmd encoded_cwd payload

    end_time="$(__rewind_now_ms)"
    start_time="${__rewind_start_time:-$end_time}"
    duration=$(( end_time - start_time ))
    cmd="${__rewind_last_cmd:-}"

    unset __rewind_start_time
    unset __rewind_last_cmd

    __rewind_should_skip "$cmd" && return 0

    sock="$(__rewind_sock_path)"

    # Try to start the daemon if the socket is missing.
    [[ -S "$sock" ]] || __rewind_daemon_start
    [[ -S "$sock" ]] || return 0

    command -v socat >/dev/null 2>&1 || return 0
    command -v python3 >/dev/null 2>&1 || return 0

    encoded_cmd="$(printf '%s' "$cmd" | __rewind_json_string)" || return 0
    encoded_cwd="$(printf '%s' "$PWD" | __rewind_json_string)" || return 0

    payload="$(printf '{"command":%s,"cwd":%s,"exit_code":%d,"duration_ms":%d}' \
        "$encoded_cmd" \
        "$encoded_cwd" \
        "$exit_code" \
        "$duration")"

    # Send from a subshell so interactive bash does not print background job ids.
    (
        printf '%s\n' "$payload" | socat - UNIX-CONNECT:"$sock"
    ) >/dev/null 2>&1 &
}

__rewind_install_hooks() {
    # Save the user's existing PROMPT_COMMAND once, then wrap it.
    if [[ -z "${__rewind_original_prompt_command+x}" ]]; then
        __rewind_original_prompt_command="${PROMPT_COMMAND:-}"
    fi

    PROMPT_COMMAND="__rewind_prompt_command"

    # Replacing the DEBUG trap makes this snippet safe to source repeatedly.
    trap '__rewind_debug_trap' DEBUG
}

__rewind_install_hooks
__rewind_daemon_start
