# rewind fish integration
# Generated by `rw init fish`.
# Install with:   rw init --install
# Remove with:    rw init --uninstall

# Make the snippet safe to source repeatedly.
functions -e __rewind_sock_dir 2>/dev/null
functions -e __rewind_sock_path 2>/dev/null
functions -e __rewind_now_ms 2>/dev/null
functions -e __rewind_json_string 2>/dev/null
functions -e __rewind_daemon_start 2>/dev/null
functions -e __rewind_should_skip 2>/dev/null
functions -e __rewind_preexec 2>/dev/null
functions -e __rewind_postexec 2>/dev/null
functions -e __rewind_chpwd 2>/dev/null

function __rewind_sock_dir
    if set -q XDG_DATA_HOME
        printf '%s\n' "$XDG_DATA_HOME/rewind"
    else
        printf '%s\n' "$HOME/.local/share/rewind"
    end
end

function __rewind_sock_path
    printf '%s\n' "$(__rewind_sock_dir)/rewind.sock"
end

function __rewind_now_ms
    python3 -c 'import time; print(int(time.time() * 1000))'
end

function __rewind_json_string
    python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
end

function __rewind_daemon_start
    set -l sock_dir (__rewind_sock_dir)
    set -l sock (__rewind_sock_path)

    # If the socket exists, assume the daemon is already available.
    test -S "$sock"; and return

    mkdir -p "$sock_dir"

    # Background and disown so fish does not show job noise.
    rw-daemon >/dev/null 2>&1 &
    disown $last_pid 2>/dev/null

    # Give the daemon a brief chance to bind before the first hook fires.
    sleep 0.05
end

function __rewind_should_skip
    set -l cmd "$argv[1]"

    test -z "$cmd"; and return 0

    switch "$cmd"
        case rw 'rw *' rw-daemon 'rw-daemon *'
            return 0
    end

    return 1
end

function __rewind_preexec --on-event fish_preexec
    set -g __rewind_start_time (__rewind_now_ms)
    set -g __rewind_last_cmd "$argv[1]"
end

function __rewind_postexec --on-event fish_postexec
    set -l exit_code $status
    set -l end_time (__rewind_now_ms)
    set -l start_time "$end_time"

    if set -q __rewind_start_time
        set start_time "$__rewind_start_time"
    end

    set -l duration (math "$end_time - $start_time")
    set -l cmd ""

    if set -q __rewind_last_cmd
        set cmd "$__rewind_last_cmd"
    end

    set -e __rewind_start_time
    set -e __rewind_last_cmd

    __rewind_should_skip "$cmd"; and return

    set -l sock (__rewind_sock_path)

    # Try to start the daemon if the socket is missing.
    test -S "$sock"; or __rewind_daemon_start
    test -S "$sock"; or return

    command -q socat; or return
    command -q python3; or return

    set -l encoded_cmd (printf '%s' "$cmd" | __rewind_json_string)
    set -l encoded_cwd (printf '%s' "$PWD" | __rewind_json_string)

    set -l payload (printf '{"command":%s,"cwd":%s,"exit_code":%d,"duration_ms":%d}' \
        "$encoded_cmd" \
        "$encoded_cwd" \
        "$exit_code" \
        "$duration")

    # Send asynchronously without surfacing hook failures to the prompt.
    begin
        printf '%s\n' "$payload" | socat - UNIX-CONNECT:"$sock"
    end >/dev/null 2>&1 &

    disown $last_pid 2>/dev/null
end

function __rewind_chpwd --on-variable PWD
    # Reserved for future per-directory daemon selection.
end

__rewind_daemon_start
