# rewind zsh integration
# Generated by `rw init zsh`.
# Install with:   rw init --install
# Remove with:    rw init --uninstall

__rewind_sock_dir() {
    print -r -- "${XDG_DATA_HOME:-$HOME/.local/share}/rewind"
}

__rewind_sock_path() {
    print -r -- "$(__rewind_sock_dir)/rewind.sock"
}

__rewind_now_ms() {
    # Prefer zsh's native time source; fall back to GNU date.
    zmodload zsh/datetime 2>/dev/null
    if [[ -n "${EPOCHREALTIME:-}" ]]; then
        printf '%.0f\n' $(( EPOCHREALTIME * 1000 ))
    else
        date +%s%3N
    fi
}

__rewind_daemon_start() {
    emulate -L zsh

    local sock_dir="$(__rewind_sock_dir)"
    local sock="$(__rewind_sock_path)"

    # If a socket exists, assume the daemon is already available.
    # The daemon itself is responsible for removing stale sockets on startup.
    [[ -S "$sock" ]] && return

    mkdir -p "$sock_dir"

    # `&!` backgrounds and disowns in zsh, avoiding `[1] 12345` job messages.
    rw-daemon >/dev/null 2>&1 &!

    # Give the daemon a brief chance to bind before the first hook fires.
    sleep 0.05
}

__rewind_json_string() {
    python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}

__rewind_should_skip() {
    emulate -L zsh

    local cmd="$1"

    [[ -z "$cmd" ]] && return 0

    # Avoid recording rewind's own commands.
    [[ "$cmd" == "rw" || "$cmd" == rw\ * ]] && return 0
    [[ "$cmd" == "rw-daemon" || "$cmd" == rw-daemon\ * ]] && return 0

    return 1
}

__rewind_precmd_exit() {
    __rewind_last_exit=$?
}

__rewind_precmd() {
    emulate -L zsh

    local exit_code="${__rewind_last_exit:-0}"
    local end_time="$(__rewind_now_ms)"
    local start_time="${__rewind_start_time:-$end_time}"
    local duration=$(( end_time - start_time ))
    local cmd="${__rewind_last_cmd:-}"

    unset __rewind_start_time
    unset __rewind_last_cmd

    __rewind_should_skip "$cmd" && return

    local sock="$(__rewind_sock_path)"

    # Try to start the daemon if the socket is missing.
    [[ -S "$sock" ]] || __rewind_daemon_start
    [[ -S "$sock" ]] || return

    command -v socat >/dev/null 2>&1 || return
    command -v python3 >/dev/null 2>&1 || return

    local encoded_cmd encoded_cwd payload

    encoded_cmd="$(print -rn -- "$cmd" | __rewind_json_string)" || return
    encoded_cwd="$(print -rn -- "$PWD" | __rewind_json_string)" || return

    payload=$(printf '{"command":%s,"cwd":%s,"exit_code":%d,"duration_ms":%d}' \
        "$encoded_cmd" \
        "$encoded_cwd" \
        "$exit_code" \
        "$duration")

    # Background + disown so zsh does not print job ids after every command.
    {
        print -r -- "$payload" | socat - UNIX-CONNECT:"$sock"
    } >/dev/null 2>&1 &!
}

__rewind_preexec() {
    __rewind_start_time="$(__rewind_now_ms)"
    __rewind_last_cmd="$1"
}

__rewind_chpwd() {
    : # Reserved for future per-directory daemon selection.
}

autoload -Uz add-zsh-hook

# Make the snippet safe to source repeatedly.
# Without this, `source ~/.zshrc` can register duplicate hooks.
add-zsh-hook -d precmd __rewind_precmd_exit 2>/dev/null
add-zsh-hook -d precmd __rewind_precmd 2>/dev/null
add-zsh-hook -d preexec __rewind_preexec 2>/dev/null
add-zsh-hook -d chpwd __rewind_chpwd 2>/dev/null

add-zsh-hook precmd __rewind_precmd_exit
add-zsh-hook precmd __rewind_precmd
add-zsh-hook preexec __rewind_preexec
add-zsh-hook chpwd __rewind_chpwd

__rewind_daemon_start
